---
deployment:
  tasks:
  # Despliegue ligero: evita npm durante deploy (úsalo desde la UI de Node.js en cPanel)
  - /bin/echo "[cPanel Deploy] Iniciando despliegue en $(/bin/pwd)"
  - /bin/mkdir -p tmp uploads
  # Reinicio de Passenger (Node app)
  - /bin/touch tmp/restart.txt
  - /bin/echo "[cPanel Deploy] Despliegue completado"
